/* Generated by Yosys 0.39+183 (git sha1 bc1499928, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

(* top =  1  *)
(* src = "cajero.v:26.1-214.10" *)
module cajero(clk, rst, tarjeta_recibida, tipo_tarjeta, pin, digito, digito_stb, tipo_transaccion, monto, monto_stb, balance_actualizado, entregar_dinero, fondos_insuficientes, pin_incorrecto, bloqueo, advertencia);
  (* src = "cajero.v:42.16-42.27" *)
  output advertencia;
  wire advertencia;
  (* src = "cajero.v:45.16-45.23" *)
  wire [31:0] balance;
  (* src = "cajero.v:37.16-37.35" *)
  output balance_actualizado;
  wire balance_actualizado;
  (* src = "cajero.v:41.16-41.23" *)
  output bloqueo;
  wire bloqueo;
  (* src = "cajero.v:27.11-27.14" *)
  input clk;
  wire clk;
  (* src = "cajero.v:48.9-48.23" *)
  wire dig_incorrecto;
  (* src = "cajero.v:32.16-32.22" *)
  input [3:0] digito;
  wire [3:0] digito;
  (* src = "cajero.v:33.11-33.21" *)
  input digito_stb;
  wire digito_stb;
  (* src = "cajero.v:38.16-38.31" *)
  output entregar_dinero;
  wire entregar_dinero;
  (* src = "cajero.v:46.15-46.28" *)
  wire [2:0] estado_actual;
  (* src = "cajero.v:47.15-47.28" *)
  wire [2:0] estado_futuro;
  (* src = "cajero.v:39.16-39.36" *)
  output fondos_insuficientes;
  wire fondos_insuficientes;
  (* src = "cajero.v:49.15-49.24" *)
  wire [2:0] ingresado;
  (* src = "cajero.v:35.18-35.23" *)
  input [31:0] monto;
  wire [31:0] monto;
  (* src = "cajero.v:36.11-36.20" *)
  input monto_stb;
  wire monto_stb;
  (* src = "cajero.v:31.18-31.21" *)
  input [15:0] pin;
  wire [15:0] pin;
  (* src = "cajero.v:40.16-40.30" *)
  output pin_incorrecto;
  wire pin_incorrecto;
  (* src = "cajero.v:28.11-28.14" *)
  input rst;
  wire rst;
  (* src = "cajero.v:29.11-29.27" *)
  input tarjeta_recibida;
  wire tarjeta_recibida;
  (* src = "cajero.v:30.11-30.23" *)
  input tipo_tarjeta;
  wire tipo_tarjeta;
  (* src = "cajero.v:34.11-34.27" *)
  input tipo_transaccion;
  wire tipo_transaccion;
  assign advertencia = 1'h0;
  assign balance = 32'd0;
  assign balance_actualizado = 1'h0;
  assign bloqueo = 1'h0;
  assign dig_incorrecto = 1'h0;
  assign entregar_dinero = 1'h0;
  assign estado_actual = 3'h0;
  assign estado_futuro = 3'h0;
  assign fondos_insuficientes = 1'h0;
  assign ingresado = 3'h0;
  assign pin_incorrecto = 1'h0;
endmodule
